name: CI/CD - DEV

on:
  push:
    branches: [ "develop" ]
    tags: [ "latest" ]
  workflow_dispatch: {}

env:
  REGISTRY: ccr.ccs.tencentyun.com
  IMAGE: ccr.ccs.tencentyun.com/quoted-com-insight/quoted-com-insight

jobs:
  build-and-push:
    name: Build and Push Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.ID_RSA }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Tencent TCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.TCR_USERNAME }}
          password: ${{ secrets.TCR_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE }}
          tags: |
            type=raw,value=latest

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Remote Deploy
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.ID_RSA }}
      - name: Deploy over SSH
        env:
          HOST: "203.195.217.95"
          USER: "ubuntu"
          IMAGE: ${{ env.IMAGE }}
        run: |
          set -eux
          ssh -o StrictHostKeyChecking=no ${USER}@${HOST} << 'EOF'
          set -eux

          docker login '${{ env.REGISTRY }}' -u '${{ secrets.TCR_USERNAME }}' -p '${{ secrets.TCR_PASSWORD }}'
          cd /opt/quoted-com-insight
          docker compose pull
          docker compose up -d --remove-orphans
          docker image prune -f || true
          EOF
